api_key: "sk-7b7a1dfac5f94b539321f3a159d0161b"
base_url: "https://api.deepseek.com"
path: "20240301"
rules: "你是一个期货类型的关键词抽取器，你只需要提取有关于期货产品的关键词，返回格式为期货策略(做空:多单持有等)，期货产品(铜:铁等)，产品状况(上涨:下跌等)\n返回一个以逗号隔开的关键词，关键词之间无需按类别排列，如果有些类型的关键词不存在则设置为unknown"
build_flag: true